//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Resources.Lang.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUA NGAY.
        /// </summary>
        internal static string ActionBuy {
            get {
                return ResourceManager.GetString("ActionBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THUÊ NGAY.
        /// </summary>
        internal static string ActionRent {
            get {
                return ResourceManager.GetString("ActionRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Thêm mới.
        /// </summary>
        internal static string AddBtn {
            get {
                return ResourceManager.GetString("AddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm phụ tùng .
        /// </summary>
        internal static string AddPartTitle {
            get {
                return ResourceManager.GetString("AddPartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa Chỉ.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm xe.
        /// </summary>
        internal static string AddVehicle {
            get {
                return ResourceManager.GetString("AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm xe thất bại! Vui lòng kiểm tra lại thông tin..
        /// </summary>
        internal static string AddVehicleFailed {
            get {
                return ResourceManager.GetString("AddVehicleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm xe thành công!.
        /// </summary>
        internal static string AddVehicleSuccess {
            get {
                return ResourceManager.GetString("AddVehicleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        internal static string AllStatus {
            get {
                return ResourceManager.GetString("AllStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành Tiền .
        /// </summary>
        internal static string AmountColumn {
            get {
                return ResourceManager.GetString("AmountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu ứng chuyển động.
        /// </summary>
        internal static string Animations {
            get {
                return ResourceManager.GetString("Animations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt.
        /// </summary>
        internal static string ApproveBtn {
            get {
                return ResourceManager.GetString("ApproveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUYỆT ĐƠN THUÊ XE .
        /// </summary>
        internal static string ApproveRentalTitle {
            get {
                return ResourceManager.GetString("ApproveRentalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHỜ DUYỆT.
        /// </summary>
        internal static string BadgeWaitApprove {
            get {
                return ResourceManager.GetString("BadgeWaitApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Sinh.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khôi phục mặc định.
        /// </summary>
        internal static string ButtonRestore {
            get {
                return ResourceManager.GetString("ButtonRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUA.
        /// </summary>
        internal static string BuyBtn {
            get {
                return ResourceManager.GetString("BuyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUA NGAY.
        /// </summary>
        internal static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hủy các thay đổi!.
        /// </summary>
        internal static string CancelConfirm {
            get {
                return ResourceManager.GetString("CancelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu ngân.
        /// </summary>
        internal static string Cashier {
            get {
                return ResourceManager.GetString("Cashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn file ảnh.
        /// </summary>
        internal static string ChooseImage {
            get {
                return ResourceManager.GetString("ChooseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa xe.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo phiếu bảo trì.
        /// </summary>
        internal static string CreateBtn {
            get {
                return ResourceManager.GetString("CreateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Tạo.
        /// </summary>
        internal static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã KH.
        /// </summary>
        internal static string CustomerID {
            get {
                return ResourceManager.GetString("CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ KHÁCH HÀNG.
        /// </summary>
        internal static string CustomerTitle {
            get {
                return ResourceManager.GetString("CustomerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ngày nhắc trước:.
        /// </summary>
        internal static string DaysBefore {
            get {
                return ResourceManager.GetString("DaysBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} ngày) .
        /// </summary>
        internal static string DaysLabel {
            get {
                return ResourceManager.GetString("DaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string DeleteBtn {
            get {
                return ResourceManager.GetString("DeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi xóa xe.
        /// </summary>
        internal static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa xe thất bại!.
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa xe thành công!.
        /// </summary>
        internal static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHI TIẾT .
        /// </summary>
        internal static string DetailBtn {
            get {
                return ResourceManager.GetString("DetailBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết phụ tùng .
        /// </summary>
        internal static string DetailTitle {
            get {
                return ResourceManager.GetString("DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        internal static string EditBtn {
            get {
                return ResourceManager.GetString("EditBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa xe.
        /// </summary>
        internal static string EditVehicle {
            get {
                return ResourceManager.GetString("EditVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa xe thất bại! Vui lòng kiểm tra lại thông tin..
        /// </summary>
        internal static string EditVehicleFailed {
            get {
                return ResourceManager.GetString("EditVehicleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa xe thành công!.
        /// </summary>
        internal static string EditVehicleSuccess {
            get {
                return ResourceManager.GetString("EditVehicleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ NHÂN VIÊN.
        /// </summary>
        internal static string EmployeeTitle {
            get {
                return ResourceManager.GetString("EmployeeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân khối.
        /// </summary>
        internal static string EngineCapacity {
            get {
                return ResourceManager.GetString("EngineCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỹ thuật.
        /// </summary>
        internal static string Engineer {
            get {
                return ResourceManager.GetString("Engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước font:.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cho thuê.
        /// </summary>
        internal static string ForRent {
            get {
                return ResourceManager.GetString("ForRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bán.
        /// </summary>
        internal static string ForSale {
            get {
                return ResourceManager.GetString("ForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm thấy.
        /// </summary>
        internal static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin xăng.
        /// </summary>
        internal static string FuelInfo {
            get {
                return ResourceManager.GetString("FuelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ Tên.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới Tính.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chung.
        /// </summary>
        internal static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi tải ảnh.
        /// </summary>
        internal static string ImageLoadError {
            get {
                return ResourceManager.GetString("ImageLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá nhập.
        /// </summary>
        internal static string ImportPrice {
            get {
                return ResourceManager.GetString("ImportPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá nhập phải là số dương!.
        /// </summary>
        internal static string ImportPricePositiveRequired {
            get {
                return ResourceManager.GetString("ImportPricePositiveRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Thông báo.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin bảo trì.
        /// </summary>
        internal static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết hạn BH.
        /// </summary>
        internal static string InsuranceExpiry {
            get {
                return ResourceManager.GetString("InsuranceExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao diện.
        /// </summary>
        internal static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khóa:.
        /// </summary>
        internal static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ / Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghỉ.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi tải cài đặt:.
        /// </summary>
        internal static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách bảo trì .
        /// </summary>
        internal static string MaintenanceListTitle {
            get {
                return ResourceManager.GetString("MaintenanceListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang bảo trì.
        /// </summary>
        internal static string MaintenanceStatus {
            get {
                return ResourceManager.GetString("MaintenanceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ BẢO TRÌ XE .
        /// </summary>
        internal static string MaintenanceTitle {
            get {
                return ResourceManager.GetString("MaintenanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý phụ tùng.
        /// </summary>
        internal static string ManagePhuTungBtn {
            get {
                return ResourceManager.GetString("ManagePhuTungBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý xe.
        /// </summary>
        internal static string ManageVehicleBtn {
            get {
                return ResourceManager.GetString("ManageVehicleBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Khách Hàng.
        /// </summary>
        internal static string MenuCustomer {
            get {
                return ResourceManager.GetString("MenuCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string MenuDashboard {
            get {
                return ResourceManager.GetString("MenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Quản Lý Nhân Viên.
        /// </summary>
        internal static string MenuEmployee {
            get {
                return ResourceManager.GetString("MenuEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Xuất.
        /// </summary>
        internal static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Xử Lý.
        /// </summary>
        internal static string MenuProcessing {
            get {
                return ResourceManager.GetString("MenuProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Sản Phẩm.
        /// </summary>
        internal static string MenuProduct {
            get {
                return ResourceManager.GetString("MenuProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Cho Thuê.
        /// </summary>
        internal static string MenuRental {
            get {
                return ResourceManager.GetString("MenuRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Bán Hàng.
        /// </summary>
        internal static string MenuSales {
            get {
                return ResourceManager.GetString("MenuSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài Đặt.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Km đã chạy.
        /// </summary>
        internal static string Mileage {
            get {
                return ResourceManager.GetString("Mileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu khách hàng.
        /// </summary>
        internal static string NoCustomerData {
            get {
                return ResourceManager.GetString("NoCustomerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có đơn nào chờ duyệt!.
        /// </summary>
        internal static string NoDataWaitApprove {
            get {
                return ResourceManager.GetString("NoDataWaitApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu nhân viên.
        /// </summary>
        internal static string NoEmployeeData {
            get {
                return ResourceManager.GetString("NoEmployeeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KHÔNG CÓ ẢNH.
        /// </summary>
        internal static string NoImage {
            get {
                return ResourceManager.GetString("NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KHÔNG CÓ QUYỀN .
        /// </summary>
        internal static string NoPermissionBtn {
            get {
                return ResourceManager.GetString("NoPermissionBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy xe nào phù hợp với điều kiện tìm kiếm!.
        /// </summary>
        internal static string NoResultFound {
            get {
                return ResourceManager.GetString("NoResultFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có xe nào sẵn sàng bán.
        /// </summary>
        internal static string NoSaleData {
            get {
                return ResourceManager.GetString("NoSaleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú: .
        /// </summary>
        internal static string NoteLabel {
            get {
                return ResourceManager.GetString("NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã tắt tất cả thông báo. Bạn có chắc chắn muốn tiếp tục?.
        /// </summary>
        internal static string NotificationWarning {
            get {
                return ResourceManager.GetString("NotificationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo khi xe sắp hết hạn bảo hiểm.
        /// </summary>
        internal static string NotifyInsurance {
            get {
                return ResourceManager.GetString("NotifyInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo khi xe sắp hết hạn đăng ký.
        /// </summary>
        internal static string NotifyRegistration {
            get {
                return ResourceManager.GetString("NotifyRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo khi khách hàng sắp hết hạn thuê.
        /// </summary>
        internal static string NotifyRental {
            get {
                return ResourceManager.GetString("NotifyRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có.
        /// </summary>
        internal static string NotYet {
            get {
                return ResourceManager.GetString("NotYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database chưa có xe nào!. Vui lòng thêm xe mới..
        /// </summary>
        internal static string NoVehicleFound {
            get {
                return ResourceManager.GetString("NoVehicleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn #{0} .
        /// </summary>
        internal static string OrderLabel {
            get {
                return ResourceManager.GetString("OrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã PT.
        /// </summary>
        internal static string PartCodeColumn {
            get {
                return ResourceManager.GetString("PartCodeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ tùng: .
        /// </summary>
        internal static string PartLabel {
            get {
                return ResourceManager.GetString("PartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Phụ Tùng .
        /// </summary>
        internal static string PartNameColumn {
            get {
                return ResourceManager.GetString("PartNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi Chú .
        /// </summary>
        internal static string PartNoteColumn {
            get {
                return ResourceManager.GetString("PartNoteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VNĐ/ngày.
        /// </summary>
        internal static string PerDay {
            get {
                return ResourceManager.GetString("PerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SĐT.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biển số: {0} .
        /// </summary>
        internal static string PlateLabel {
            get {
                return ResourceManager.GetString("PlateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập đầy đủ thông tin!.
        /// </summary>
        internal static string PleaseEnterFullInfo {
            get {
                return ResourceManager.GetString("PleaseEnterFullInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập đúng và hợp lệ!.
        /// </summary>
        internal static string PleaseEnterValidInfo {
            get {
                return ResourceManager.GetString("PleaseEnterValidInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn xe cần xóa!.
        /// </summary>
        internal static string PleaseSelectVehicleToDelete {
            get {
                return ResourceManager.GetString("PleaseSelectVehicleToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn xe cần sửa!.
        /// </summary>
        internal static string PleaseSelectVehicleToEdit {
            get {
                return ResourceManager.GetString("PleaseSelectVehicleToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ .
        /// </summary>
        internal static string PriceContact {
            get {
                return ResourceManager.GetString("PriceContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá mua phải là số dương!.
        /// </summary>
        internal static string PricePositiveRequired {
            get {
                return ResourceManager.GetString("PricePositiveRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ SẢN PHẨM.
        /// </summary>
        internal static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua.
        /// </summary>
        internal static string PurchaseDate {
            get {
                return ResourceManager.GetString("PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá mua.
        /// </summary>
        internal static string PurchasePrice {
            get {
                return ResourceManager.GetString("PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mục đích.
        /// </summary>
        internal static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Lượng .
        /// </summary>
        internal static string QtyColumn {
            get {
                return ResourceManager.GetString("QtyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Còn: {0} xe.
        /// </summary>
        internal static string QuantityLabel {
            get {
                return ResourceManager.GetString("QuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sẵn sàng.
        /// </summary>
        internal static string ReadyStatus {
            get {
                return ResourceManager.GetString("ReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số bản ghi: {0}.
        /// </summary>
        internal static string RecordCount {
            get {
                return ResourceManager.GetString("RecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm mới.
        /// </summary>
        internal static string RefreshBtn {
            get {
                return ResourceManager.GetString("RefreshBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đăng ký.
        /// </summary>
        internal static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết hạn ĐK.
        /// </summary>
        internal static string RegistrationExpiry {
            get {
                return ResourceManager.GetString("RegistrationExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ Chối .
        /// </summary>
        internal static string RejectBtn {
            get {
                return ResourceManager.GetString("RejectBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string RemoveBtnColumn {
            get {
                return ResourceManager.GetString("RemoveBtnColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang thuê.
        /// </summary>
        internal static string RentedStatus {
            get {
                return ResourceManager.GetString("RentedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THUÊ NGAY.
        /// </summary>
        internal static string RentNow {
            get {
                return ResourceManager.GetString("RentNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Bạn có chắc chắn muốn khôi phục cài đặt về mặc định?.
        /// </summary>
        internal static string RestoreConfirm {
            get {
                return ResourceManager.GetString("RestoreConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã khôi phục cài đặt mặc định!.
        /// </summary>
        internal static string RestoreSuccess {
            get {
                return ResourceManager.GetString("RestoreSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ BÁN HÀNG .
        /// </summary>
        internal static string SaleTitle {
            get {
                return ResourceManager.GetString("SaleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi lưu cài đặt:.
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu cài đặt thành công!.
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        internal static string SaveSuccessTitle {
            get {
                return ResourceManager.GetString("SaveSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm.
        /// </summary>
        internal static string SearchBtn {
            get {
                return ResourceManager.GetString("SearchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm theo:.
        /// </summary>
        internal static string SearchBy {
            get {
                return ResourceManager.GetString("SearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ảnh xe.
        /// </summary>
        internal static string SelectVehicleImage {
            get {
                return ResourceManager.GetString("SelectVehicleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã bán.
        /// </summary>
        internal static string SoldStatus {
            get {
                return ResourceManager.GetString("SoldStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp.
        /// </summary>
        internal static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt Đơn Thuê .
        /// </summary>
        internal static string TabApproveRental {
            get {
                return ResourceManager.GetString("TabApproveRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Cho Thuê .
        /// </summary>
        internal static string TabManageRental {
            get {
                return ResourceManager.GetString("TabManageRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin kỹ thuật.
        /// </summary>
        internal static string TechnicalInfo {
            get {
                return ResourceManager.GetString("TechnicalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên kỹ thuật: .
        /// </summary>
        internal static string TechnicianLabel {
            get {
                return ResourceManager.GetString("TechnicianLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Theme:.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự động.
        /// </summary>
        internal static string ThemeAuto {
            get {
                return ResourceManager.GetString("ThemeAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tối.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sáng.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TỔNG CHI PHÍ: .
        /// </summary>
        internal static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số xe.
        /// </summary>
        internal static string TotalVehicles {
            get {
                return ResourceManager.GetString("TotalVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng: {0} đơn chờ duyệt.
        /// </summary>
        internal static string TotalWaitApprove {
            get {
                return ResourceManager.GetString("TotalWaitApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thử việc.
        /// </summary>
        internal static string Trial {
            get {
                return ResourceManager.GetString("Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐVT.
        /// </summary>
        internal static string UnitColumn {
            get {
                return ResourceManager.GetString("UnitColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập Nhật.
        /// </summary>
        internal static string UpdatedDate {
            get {
                return ResourceManager.GetString("UpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn Giá .
        /// </summary>
        internal static string UsagePriceColumn {
            get {
                return ResourceManager.GetString("UsagePriceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG TIN CHI TIẾT XE MÁY.
        /// </summary>
        internal static string VehicleDetailTitle {
            get {
                return ResourceManager.GetString("VehicleDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xe không được để trống!.
        /// </summary>
        internal static string VehicleIDRequired {
            get {
                return ResourceManager.GetString("VehicleIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe:.
        /// </summary>
        internal static string VehicleLabel {
            get {
                return ResourceManager.GetString("VehicleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin xe!.
        /// </summary>
        internal static string VehicleNotFound {
            get {
                return ResourceManager.GetString("VehicleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xe.
        /// </summary>
        internal static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ XE.
        /// </summary>
        internal static string VehicleTitle {
            get {
                return ResourceManager.GetString("VehicleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại xe.
        /// </summary>
        internal static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        internal static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Hợp Đồng.
        /// </summary>
        internal static string ViewContractBtn {
            get {
                return ResourceManager.GetString("ViewContractBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Chi Tiết .
        /// </summary>
        internal static string ViewDetailBtn {
            get {
                return ResourceManager.GetString("ViewDetailBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh báo.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XE TRÙNG LỊCH! .
        /// </summary>
        internal static string WarningConflict {
            get {
                return ResourceManager.GetString("WarningConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐƠN ĐÃ QUÁ HẠN! .
        /// </summary>
        internal static string WarningOverdue {
            get {
                return ResourceManager.GetString("WarningOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang làm việc.
        /// </summary>
        internal static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm SX.
        /// </summary>
        internal static string YearOfManufacture {
            get {
                return ResourceManager.GetString("YearOfManufacture", resourceCulture);
            }
        }
    }
}
